Improved zerobufCxx.py for ipp files generation
HBPVIS/ZeroBuf pull request #84
Opened 2017-05-31 12:43 UTC by gonkc

Hello, I'm Gonzalo Bayo, from the group working back in URJC/UPM with Pablo Toharia. Right now I'm trying to use **ZeroBuf** in a custom C++ project in Windows and the generated ipp files don't compile if we use this library in more than one project. Visual Studio compiler reject the compilation with an LNK2005( function/method already defined ).
Modifying the _zerobufCxx.py_ file by adding the "inline" keyword before function definitions on ipp files could be an option to fix this and make errors disappear.
Regards

2017-05-31 14:40 UTC, gonkc commented on bin/zerobufCxx.py
> +                    (classname + '::') if classname else '', impl_function))
Fixed with a new parameter on format string.

2017-05-31 15:09 UTC, rdumusc commented
looks OK to me, but we have to remove shallow = true from .gitmodules to make CI pass

2017-06-01 11:13 UTC, gonkc commented
We've getting some errors making the compilation with cpp files with 'inline' keyword. To solve that, 'inline' keyword only is used on inline implementations (ipp files).
Regards

2017-06-01 15:54 UTC, rdumusc requested changes
Thanks for the fix. Please rebase your PR on https://github.com/HBPVIS/ZeroBuf/pull/85 to fix the CI build, which is needed for merging.

2017-06-01 15:54 UTC, rdumusc commented on bin/zerobufCxx.py
> +inline_implementation = False
Unless there is a good reason for this global "option" I would remove it and always add inline

2017-06-02 12:02 UTC, gonkc commented on bin/zerobufCxx.py
> +inline_implementation = False
I think that it won't work. In Linux these functions are not inline and I would not force the use of inline functions.

2017-06-02 14:04 UTC, tribal-tec commented on bin/zerobufCxx.py
> +inline_implementation = False
Please check https://github.com/HBPVIS/ZeroBuf/commit/7ab0058e24cc262eb95a27a344b4a6bee78429cf; there is already enough code to decide if to use inline on Windows, and not-inline everywhere else. I wonder why I forgot the inline back then, it seemed to have worked, but that's obviously not working.

2017-06-05 09:52 UTC, gonkc commented on bin/zerobufCxx.py
> +inline_implementation = False
Removed global default value of inline_implementation and global keyword. Only needed read access to variable.

2017-06-06 08:09 UTC, tribal-tec commented on bin/zerobufCxx.py
> +            if inline_implementation is True:
no need to compare against 'True'

2017-06-06 08:09 UTC, dnachbaur approved these changes
Good otherwise. Thx for the fix!

2017-06-06 10:24 UTC, gonkc commented on bin/zerobufCxx.py
> +            if inline_implementation is True:
That's right, I forgot to remove it. Now it's fixed. Thanks.

2017-06-06 11:02 UTC, gonkc commented on bin/zerobufCxx.py
> +inline_implementation = False
@rdumusc , review this change, please. Thanks.

2017-06-06 11:32 UTC, rdumusc approved these changes

2017-06-06 11:33 UTC, rdumusc commented
retest this please

2017-06-06 11:35 UTC, merged